services:
- type: web
  name: next-js
  runtime: node
  plan: starter
  buildCommand: npm; npm build
  startCommand: npm start
  autoDeploy: true
  envVars:
  - key: NODE_ENV
    value: production
# Uncomment the following to deploy this app as a static site on render

